import type { User } from '../types/identity';

export const users: User[] = [
  {
    id: 'user-requester',
    email: 'requester@paperwork.local',
    displayName: 'Basic Requester',
    initials: 'BR',
    departmentId: 'dept-finance',
    roles: {
      canStartRequests: true,
      isApprover: false,
      canManageWorkflows: false,
      isOrgAdmin: false,
    },
  },
  {
    id: 'user-approver',
    email: 'approver@paperwork.local',
    displayName: 'Requester + Approver',
    initials: 'RA',
    departmentId: 'dept-finance',
    roles: {
      canStartRequests: true,
      isApprover: true,
      canManageWorkflows: false,
      isOrgAdmin: false,
    },
  },
  {
    id: 'user-owner',
    email: 'owner@paperwork.local',
    displayName: 'Workflow Owner',
    initials: 'WO',
    departmentId: 'dept-hr',
    roles: {
      canStartRequests: true,
      isApprover: false,
      canManageWorkflows: true,
      isOrgAdmin: false,
    },
  },
  {
    id: 'user-power',
    email: 'power@paperwork.local',
    displayName: 'Power User',
    initials: 'PU',
    departmentId: 'dept-legal',
    roles: {
      canStartRequests: true,
      isApprover: true,
      canManageWorkflows: true,
      isOrgAdmin: false,
    },
  },
  {
    id: 'user-admin',
    email: 'admin@paperwork.local',
    displayName: 'Organisation Admin',
    initials: 'OA',
    departmentId: 'dept-hr',
    roles: {
      canStartRequests: true,
      isApprover: true,
      canManageWorkflows: true,
      isOrgAdmin: true,
    },
  },
  {
    id: 'user-eng-lead',
    email: 'alice.chen@paperwork.local',
    displayName: 'Alice Chen',
    initials: 'AC',
    departmentId: 'dept-engineering',
    roles: {
      canStartRequests: true,
      isApprover: true,
      canManageWorkflows: true,
      isOrgAdmin: false,
    },
  },
  {
    id: 'user-med-director',
    email: 'bob.smith@paperwork.local',
    displayName: 'Bob Smith',
    initials: 'BS',
    departmentId: 'dept-medicine',
    roles: {
      canStartRequests: true,
      isApprover: true,
      canManageWorkflows: false,
      isOrgAdmin: false,
    },
  },
  {
    id: 'user-business-analyst',
    email: 'carol.williams@paperwork.local',
    displayName: 'Carol Williams',
    initials: 'CW',
    departmentId: 'dept-business',
    roles: {
      canStartRequests: true,
      isApprover: false,
      canManageWorkflows: false,
      isOrgAdmin: false,
    },
  },
  {
    id: 'user-arts-coord',
    email: 'david.brown@paperwork.local',
    displayName: 'David Brown',
    initials: 'DB',
    departmentId: 'dept-arts',
    roles: {
      canStartRequests: true,
      isApprover: false,
      canManageWorkflows: false,
      isOrgAdmin: false,
    },
  },
  {
    id: 'user-science-mgr',
    email: 'emma.davis@paperwork.local',
    displayName: 'Emma Davis',
    initials: 'ED',
    departmentId: 'dept-sciences',
    roles: {
      canStartRequests: true,
      isApprover: true,
      canManageWorkflows: false,
      isOrgAdmin: false,
    },
  },
];
